### ISSUE TITLE
USER STORY: View and Edit account profile

### ISSUE THREAD

**Issue by kkwong44** [kkwong44/kki-frontend#11]
As a **Registered User** I can **access to my profile** so that **I can update my account profile**

## Acceptance Criteria 1
**Given** that I am a registered user
**When** I want to update my profile
**Then** I can access to my profile page to perform update

## Tasks
- [x] Task 1 – Create a link to access the user profile page
- [x] Task 2 – Check current user and retrieve data to the form
- [x] Task 3 – Allow edit and save changes

## EPIC
1. #10
