### ISSUE TITLE
USER STORY: Navigation Bar

### ISSUE THREAD

**Issue by kkwong44** [kkwong44/kki-frontend#21]
As a **User** I can **view a nav bar from every page** so that **I can navigate easily between pages**

## Acceptance Criteria 1
**Given** that the site has several url pages
**When** user want to navigate the site
**Then** it will be helpful to have a navigation bar

## Tasks
- [x] Task 1 – Create a navigation bar on to of the site
- [x] Task 2 – Collapse the navigation bar to menu bar on smaller devices
- [x] Task 3 –  Install React Router 'npm install react-router-dom@5.3.0'
- [x] Task 4 –  Add basic navigation menu items and expand as necessary

## EPIC
1. #20
