### ISSUE TITLE
USER STORY: Edit and Delete Albums

### ISSUE THREAD

**Issue by kkwong44** [kkwong44/kki-frontend#26]
As a **Owner** I can **edit and delete albums** so that **I can update or remove album from the app**

## Acceptance Criteria 1
**Given** that I am the owner of a album
**When** I want to edit or delete the album
**Then** it should have the facility to do that

## Tasks
- [x] Task 1 – Check album's owner
- [x] Task 2 – Create edit button in album
- [x] Task 3 – Create delete button in album
- [x] Task 4 – Check, confirm and save changes

## EPIC
1. #24
