### ISSUE TITLE
USER STORY: Popular albums

### ISSUE THREAD

**Issue by kkwong44** [kkwong44/kki-frontend#27]
As a **Registered User** I can **see a list of the most liked albums** so that **I can see which albums are popular**

## Acceptance Criteria 1
**Given** that there are popular albums
**When** we want to tell the user
**Then** it should shows as a sidebar item

## Tasks
- [x] Task 1 – Count the likes in each album
- [x] Task 2 – Fetch the top 5 albums that has most likes
- [x] Task 3 – Display these albums as a list

## EPIC
1. #24
