### ISSUE TITLE
USER STORY: Like and unlike albums

### ISSUE THREAD

**Issue by kkwong44** [kkwong44/kki-frontend#33]
As a **Logged in user** I can **like or unlike individual album** so that **it can provide feedback about the popularity of this album**

## Acceptance Criteria 1
**Given** that we want to provide static on a album
**When** a user like or unlike an album
**Then** the user can toggle this status on each album

## Tasks
- [x] Task 1 – Create a like icon on each album
- [x] Task 2 – Each user can toggle the status on each album
- [x] Task 3 – Count and update all likes on each album

## EPIC
1. #29
