### ISSUE TITLE
USER STORY: Album Photos

### ISSUE THREAD

**Issue by kkwong44** [kkwong44/kki-frontend#35]
As a **User** I can **select an album** so that **I can view the album photos**

## Acceptance Criteria 1
**Given** that I have logged into the app
**When** I select an an album
**Then** it allows me to see the album's photos

## Tasks
- [x] Task 1 – Check credential
- [x] Task 2 – Create link from album to album's photo page
- [x] Task 3 – Display photos as a list

## EPIC
1. #34
