### ISSUE TITLE
USER STORY: Delete Photos

### ISSUE THREAD

**Issue by kkwong44** [kkwong44/kki-frontend#37]
As a **Owner** I can **delete photos from the album** so that **the photos are no longer available on the app**

## Acceptance Criteria 1
**Given** that I am the owner of the album
**When** I want to remove photos
**Then** it allows me to delete photos

## Tasks
- [x] Task 1 – Check credential
- [x] Task 2 – Create Delete button for the post
- [x] Task 3 – Confirm and delete

## EPIC
1. #34
