### ISSUE TITLE
USER STORY: Like and unlike photos

### ISSUE THREAD

**Issue by kkwong44** [kkwong44/kki-frontend#40]
As a **Logged in user** I can **like or unlike individual photo from an album** so that **it can provide feedback about the popularity of this photo**

## Acceptance Criteria 1
**Given** that we want to provide static on a photo
**When** a user like or unlike an album
**Then** the user can toggle this status on each photo

## Tasks
- [ ] Task 1 – Create a like icon on each photo
- [ ] Task 2 – Each user can toggle the status on each photo
- [ ] Task 3 – Count and update all likes on each photo

## EPIC
1. #34
