### ISSUE TITLE
USER STORY: Edit Comments

### ISSUE THREAD

**Issue by kkwong44** [kkwong44/kki-frontend#44]
As a **Owner** I can **select my own comments** so that **I can edit and update my comments**

## Acceptance Criteria 1
**Given** that I am the owner of a comment
**When** I want to edit the comment
**Then** it allow me to edit and update the comment

## Tasks
- [x] Task 1 – Check comment's owner
- [x] Task 2 – Create edit button in comment
- [x] Task 3 – Check, confirm and save changes

## EPIC
1. #41
