### ISSUE TITLE
USER STORY: Delete Comments

### ISSUE THREAD

**Issue by kkwong44** [kkwong44/kki-frontend#45]
As a **Owner** I can **select my own comments** so that **I can delete my comments**

## Acceptance Criteria 1
**Given** that I am the owner of the comment
**When** I want to remove the comment
**Then** it allows me to delete the comment

## Tasks
- [x] Task 1 – Check comment's owner
- [x] Task 2 – Create delete button in comment
- [x] Task 3 – Check, confirm and save changes

## EPIC
1. #41
