### ISSUE TITLE
USER STORY: Contact Page

### ISSUE THREAD

**Issue by kkwong44** [kkwong44/kki-frontend#49]
As a **User** I can **contact the support team** so that **I can send my queries to them**

## Acceptance Criteria 1
**Given** that this is a service app
**When** user want to contact the site
**Then** we can provide the contact details

## Tasks
- [x] Task 1 – Create a contact page
- [x] Task 2 – Allow user to click on email link and launch email client
- [x] Task 3 – Allow administrator to change contact details 

## EPIC
1. #47
