### ISSUE TITLE
USER STORY: Sign up

### ISSUE THREAD

**Issue by kkwong44** [kkwong44/kki-frontend#6]
As a **Unregistered user** I can **register as a member** so that **I can access to the photographers' albums**

## Acceptance Criteria 1
**Given** that I am an unregistered user
**When** I am on any page
**Then** I can see a link from the navigation bar to sign up

## Acceptance Criteria 2
**Given** that I see the sign-up link
**When** I click on the link
**Then** I am taken to the user registration page

## Acceptance Criteria 3
**Given** that I am in the user registration page
**When** I submit valid username, email address and password
**Then** the system creates me an account and allows me to sign in

## Tasks
- [x] Task 1 – Use Django library to develop registration process (install axios)
- [x] Task 2 – Create a button in the nav bar to direct users to the registration page
- [x] Task 3 – Create registration form
- [x] Task 4 – Validate registration details
- [x] Task 5 – Remove the register button from the nav bar when users are successfully logged in

## EPIC
1. #4
